[package]
name = "qbe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_builder = "0.12"
thiserror = "1.0"
paste = "1.0"
tempfile = { version = "3", optional = true }

[features]
default = [ "qbe-command" ]
qbe-command = ["dep:tempfile"]
