[package]
name = "qbe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_builder = { version = "0.12", default-features = false }
thiserror = { version = "1.0", optional = true }
paste = "1.0"
cfg-if = "1.0"
tempfile = { version = "3", optional = true }

[features]
default = ["qbe-command", "non-static-names", "early-return", "std", "thiserror"]
qbe-command = ["dep:tempfile", "std"]
non-static-names = ["std"]
early-return = ["std"]
std = ["derive_builder/std"]
thiserror = ["std", "dep:thiserror"]
